// Firebase-backed compatibility layer using Firebase REST APIs.
import { decodeDoc, encodeFields, firestoreFetch, toFirestoreValue } from '@/lib/firebase';

export type UserRole = 'student' | 'faculty' | 'technician' | 'supervisor' | 'admin';
export type ComplaintStatus = 'submitted' | 'verified' | 'assigned' | 'in_progress' | 'resolved' | 'closed' | 'rejected';
export type ComplaintPriority = 'low' | 'medium' | 'high' | 'emergency';

export interface Profile { id: string; full_name: string; college_id?: string; role: UserRole; department?: string; hostel?: string; block?: string; room?: string; phone?: string; avatar_url?: string; is_active: boolean; created_at: string; updated_at: string; technician?: Technician; }
export interface Building { id: string; name: string; code?: string; type: string; floors: number; description?: string; }
export interface ComplaintCategory { id: string; name: string; icon: string; color: string; description?: string; sla_hours: number; }
export interface Complaint { id: string; complaint_no: string; title: string; description: string; category_id: string; user_id: string; building_id?: string; room_id?: string; floor?: number; location_description?: string; priority: ComplaintPriority; status: ComplaintStatus; photo_urls: string[]; assigned_to?: string; assigned_at?: string; resolved_at?: string; closed_at?: string; expected_completion?: string; escalation_level: number; feedback_rating?: number; feedback_comment?: string; created_at: string; updated_at: string; complaint_categories?: ComplaintCategory; buildings?: Building; profiles?: Profile; assigned_profile?: Profile; }
export interface WorkOrder { id: string; work_order_no: string; complaint_id: string; technician_id?: string; tools_required: string[]; materials_used: { name: string; quantity: number; cost: number }[]; start_time?: string; completion_time?: string; labour_hours?: number; repair_notes?: string; material_cost: number; status: string; completion_photo_urls: string[]; created_by: string; created_at: string; updated_at: string; complaints?: Complaint; profiles?: Profile; }
export interface InventoryItem { id: string; name: string; category: string; unit: string; current_stock: number; min_stock: number; max_stock: number; unit_cost: number; supplier?: string; description?: string; }
export interface PreventiveSchedule { id: string; title: string; description?: string; category: string; building_id?: string; frequency_days: number; last_performed?: string; next_due?: string; assigned_to?: string; status: string; buildings?: Building; }
export interface Technician { id: string; employee_code?: string; skills: string[]; current_workload: number; availability_status: string; area_coverage: string[]; }
export interface Notification { id: string; user_id: string; title: string; message: string; type: string; related_id?: string; is_read: boolean; created_at: string; }

type Filter = { field: string; op: 'eq' | 'in'; value: unknown };
type Result<T = any> = { data: T | null; error: { message: string } | null };
const nowIso = () => new Date().toISOString();

async function getOne(table: string, id?: string) { if (!id) return undefined; try { return decodeDoc(await firestoreFetch(`/${table}/${id}`)); } catch { return undefined; } }
async function enrich(table: string, rows: any[]) { return Promise.all(rows.map(async r => { const row={...r}; if(table==='complaints'){row.complaint_categories=await getOne('complaint_categories',row.category_id);row.buildings=await getOne('buildings',row.building_id);row.profiles=await getOne('profiles',row.assigned_to);row.assigned_profile=row.profiles;} else if(table==='work_orders'){row.complaints=await getOne('complaints',row.complaint_id);row.profiles=await getOne('profiles',row.technician_id);} else if(table==='preventive_maintenance_schedules'){row.buildings=await getOne('buildings',row.building_id);} else if(table==='profiles'&&row.role==='technician'){row.technician=await getOne('technicians',row.id);} return row;})); }

class FirebaseQueryBuilder {
 private action:'select'|'insert'|'update'|'delete'='select'; private payload:any=null; private filters:Filter[]=[]; private sort?:{field:string;ascending:boolean}; private max?:number; private one:'single'|'maybeSingle'|null=null;
 constructor(private table:string){} select(_='*'){this.action='select';return this;} insert(v:any){this.action='insert';this.payload=v;return this;} update(v:any){this.action='update';this.payload=v;return this;} delete(){this.action='delete';return this;} eq(field:string,value:unknown){this.filters.push({field,op:'eq',value});return this;} in(field:string,value:unknown[]){this.filters.push({field,op:'in',value});return this;} order(field:string,o?:{ascending?:boolean}){this.sort={field,ascending:o?.ascending!==false};return this;} limit(v:number){this.max=v;return this;} single(){this.one='single';return this;} maybeSingle(){this.one='maybeSingle';return this;}
 then<TResult1=Result,TResult2=never>(ok?:((v:Result)=>TResult1|PromiseLike<TResult1>)|null,bad?:((r:any)=>TResult2|PromiseLike<TResult2>)|null){return this.execute().then(ok,bad);}
 private structuredQuery(){const sq:any={from:[{collectionId:this.table}]}; const fs=this.filters.map(f=>({fieldFilter:{field:{fieldPath:f.field},op:f.op==='eq'?'EQUAL':'IN',value:f.op==='in'?{arrayValue:{values:(f.value as any[]).map(toFirestoreValue)}}:toFirestoreValue(f.value)}})); if(fs.length===1)sq.where=fs[0];else if(fs.length>1)sq.where={compositeFilter:{op:'AND',filters:fs}};if(this.sort)sq.orderBy=[{field:{fieldPath:this.sort.field},direction:this.sort.ascending?'ASCENDING':'DESCENDING'}];if(this.max)sq.limit=this.max;return {structuredQuery:sq};}
 private async list(){const j=await firestoreFetch(':runQuery',{method:'POST',body:JSON.stringify(this.structuredQuery())});return (j as any[]).filter(x=>x.document).map(x=>decodeDoc(x.document));}
 private async execute():Promise<Result>{try{if(this.action==='insert'){const values=Array.isArray(this.payload)?this.payload:[this.payload];const made=[];for(const raw of values){const value={created_at:nowIso(),updated_at:nowIso(),...raw};let id=value.id as string|undefined;delete value.id;if(id){const d=await firestoreFetch(`/${this.table}/${id}`,{method:'PATCH',body:JSON.stringify(encodeFields(value))});made.push(decodeDoc(d));}else{const d=await firestoreFetch(`/${this.table}`,{method:'POST',body:JSON.stringify(encodeFields(value))});made.push(decodeDoc(d));}}const data=await enrich(this.table,made);return{data:this.one?data[0]??null:data,error:null};}
 const rows=await this.list();if(this.action==='update'||this.action==='delete'){for(const r of rows){if(this.action==='delete')await firestoreFetch(`/${this.table}/${r.id}`,{method:'DELETE'});else await firestoreFetch(`/${this.table}/${r.id}`,{method:'PATCH',body:JSON.stringify(encodeFields({...this.payload,updated_at:nowIso()}))});}return{data:null,error:null};}
 const data=await enrich(this.table,rows);if(this.one==='single'&&data.length!==1)return{data:null,error:{message:`Expected one ${this.table} record, found ${data.length}.`}};return{data:this.one?data[0]??null:data,error:null};}catch(e){return{data:null,error:{message:e instanceof Error?e.message:String(e)}};}}
}
export const supabase={from(table:string){return new FirebaseQueryBuilder(table);}};
