services:
  - type: web
    name: campusfix-api
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM
        value: CampusFix CCMMS <onboarding@resend.dev>
      - key: APP_NAME
        value: CampusFix CCMMS
  - type: web
    name: campusfix-web
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
