plugins {
    id 'com.android.application'
}

def ccmmsWebUrl = 'https://campusfix-app-x04t.onrender.com'

android {
    namespace 'com.ccmms.campusfix'
    compileSdk 35

    defaultConfig {
        applicationId 'com.ccmms.campusfix'
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName '1.0.0'

        buildConfigField 'String', 'WEB_URL', '"' + ccmmsWebUrl + '"'
    }

    buildFeatures {
        buildConfig true
    }

    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-debug'
            debuggable true
        }
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        resources {
            excludes += ['/META-INF/{AL2.0,LGPL2.1}']
        }
    }
}
